# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Notes from Nerdy Nicki
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Don't mind me...just learning to code....
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://https://thenerdynicki.github.io" # the base hostname & protocol for your site
twitter_username: thechemofquirk
github_username:  thenerdynicki

# Build settings
markdown: kramdown
